### ISSUE TITLE
there are 4 errors in test of regression

### ISSUE THREAD

**Issue by hnusttyj530** [cybertec-postgresql/postgres#10]
============== running regression test queries        ==============
test undoxacttest                 ... ok           65 ms
test tablespace                   ... ok          268 ms
parallel group (20 tests):  boolean char name int4 txid varchar int2 int8 pg_lsn text oid uuid money float4 enum bit float8 regproc numeric rangetypes
     boolean                      ... ok          111 ms
     char                         ... ok          111 ms
     name                         ... ok           68 ms
     varchar                      ... ok           60 ms
     text                         ... ok           70 ms
     int2                         ... ok           64 ms
     int4                         ... ok           58 ms
     int8                         ... ok           63 ms
     oid                          ... ok           70 ms
     float4                       ... ok           88 ms
     float8                       ... ok          101 ms
     bit                          ... ok           97 ms
     numeric                      ... ok          228 ms
     txid                         ... ok           56 ms
     uuid                         ... ok           72 ms
     enum                         ... ok           83 ms
     money                        ... ok           81 ms
     rangetypes                   ... ok          315 ms
     pg_lsn                       ... ok           58 ms
     regproc                      ... ok           70 ms
parallel group (20 tests):  lseg path circle numerology timetz time line macaddr point macaddr8 inet create_function_0 interval date strings multirangetypes box polygon timestamp timestamptz
     strings                      ... ok          121 ms
     numerology                   ... ok           34 ms
     point                        ... ok           51 ms
     lseg                         ... ok           24 ms
     line                         ... ok           43 ms
     box                          ... ok          225 ms
     path                         ... ok           28 ms
     polygon                      ... ok          246 ms
     circle                       ... ok           31 ms
     date                         ... ok           63 ms
     time                         ... ok           39 ms
     timetz                       ... ok           34 ms
     timestamp                    ... ok          358 ms
     timestamptz                  ... ok          464 ms
     interval                     ... ok           60 ms
     inet                         ... ok           51 ms
     macaddr                      ... ok           47 ms
     macaddr8                     ... ok           48 ms
     multirangetypes              ... ok          197 ms
     create_function_0            ... ok           56 ms
parallel group (12 tests):  comments misc_sanity xid tstypes unicode horology expressions mvcc geometry type_sanity opr_sanity regex
     geometry                     ... ok           95 ms
     horology                     ... ok           92 ms
     tstypes                      ... ok           72 ms
     regex                        ... ok          432 ms
     type_sanity                  ... ok           99 ms
     opr_sanity                   ... FAILED      260 ms
     misc_sanity                  ... ok           62 ms
     comments                     ... ok           40 ms
     expressions                  ... ok           91 ms
     unicode                      ... ok           72 ms
     xid                          ... ok           64 ms
     mvcc                         ... ok           91 ms
test create_function_1            ... ok           15 ms
test create_type                  ... ok           31 ms
test create_table                 ... ok          320 ms
test create_function_2            ... ok           21 ms
parallel group (5 tests):  copyselect copydml insert_conflict insert copy
     copy                         ... ok          405 ms
     copyselect                   ... ok           33 ms
     copydml                      ... ok           37 ms
     insert                       ... ok          281 ms
     insert_conflict              ... ok          128 ms
parallel group (3 tests):  create_operator create_procedure create_misc
     create_misc                  ... ok           78 ms
     create_operator              ... ok           26 ms
     create_procedure             ... ok           46 ms
parallel group (5 tests):  index_including create_view index_including_gist create_index_spgist create_index
     create_index                 ... ok          737 ms
     create_index_spgist          ... ok          379 ms
     create_view                  ... ok          238 ms
     index_including              ... ok          154 ms
     index_including_gist         ... ok          293 ms
parallel group (16 tests):  create_cast errors roleattributes create_aggregate drop_if_exists hash_func select typed_table create_am create_function_3 constraints infinite_recurse vacuum inherit updatable_views triggers
     create_aggregate             ... ok           46 ms
     create_function_3            ... ok          119 ms
     create_cast                  ... ok           23 ms
     constraints                  ... ok          171 ms
     triggers                     ... ok          727 ms
     select                       ... ok           94 ms
     inherit                      ... ok          473 ms
     typed_table                  ... ok           94 ms
     vacuum                       ... ok          315 ms
     drop_if_exists               ... ok           67 ms
     updatable_views              ... ok          474 ms
     roleattributes               ... ok           43 ms
     create_am                    ... FAILED      104 ms
     hash_func                    ... ok           66 ms
     errors                       ... ok           38 ms
     infinite_recurse             ... ok          289 ms
test sanity_check                 ... ok          161 ms
parallel group (20 tests):  select_distinct_on select_having delete random select_implicit namespace case select_into prepared_xacts transactions select_distinct portals subselect union arrays hash_index update aggregates join btree_index
     select_into                  ... ok           72 ms
     select_distinct              ... ok          155 ms
     select_distinct_on           ... ok           30 ms
     select_implicit              ... ok           47 ms
     select_having                ... ok           38 ms
     subselect                    ... ok          179 ms
     union                        ... ok          194 ms
     case                         ... ok           57 ms
     join                         ... ok          569 ms
     aggregates                   ... ok          551 ms
     transactions                 ... ok          119 ms
     random                       ... ok           44 ms
     portals                      ... ok          155 ms
     arrays                       ... ok          219 ms
     btree_index                  ... ok         1040 ms
     hash_index                   ... ok          413 ms
     update                       ... ok          435 ms
     delete                       ... ok           38 ms
     namespace                    ... ok           46 ms
     prepared_xacts               ... ok           79 ms
parallel group (20 tests):  init_privs drop_operator security_label lock tablesample object_address replica_identity password collate identity groupingsets matview generated rowsecurity privileges gist spgist gin join_hash brin
     brin                         ... ok         1396 ms
     gin                          ... ok          701 ms
     gist                         ... ok          666 ms
     spgist                       ... ok          669 ms
     privileges                   ... ok          621 ms
     init_privs                   ... ok           21 ms
     security_label               ... ok           37 ms
     collate                      ... ok          138 ms
     matview                      ... ok          283 ms
     lock                         ... ok           65 ms
     replica_identity             ... ok          114 ms
     rowsecurity                  ... ok          517 ms
     object_address               ... ok           94 ms
     tablesample                  ... ok           79 ms
     groupingsets                 ... ok          259 ms
     drop_operator                ... ok           24 ms
     password                     ... ok          116 ms
     identity                     ... ok          207 ms
     generated                    ... ok          383 ms
     join_hash                    ... ok         1384 ms
parallel group (2 tests):  brin_bloom brin_multi
     brin_bloom                   ... ok           89 ms
     brin_multi                   ... ok          184 ms
parallel group (14 tests):  dbsize collate.icu.utf8 async alter_operator tidrangescan tid tsrf tidscan misc_functions alter_generic sysviews misc incremental_sort create_table_like
     create_table_like            ... ok          211 ms
     alter_generic                ... ok           88 ms
     alter_operator               ... ok           34 ms
     misc                         ... ok          104 ms
     async                        ... ok           31 ms
     dbsize                       ... ok           19 ms
     misc_functions               ... ok           77 ms
     sysviews                     ... ok           88 ms
     tsrf                         ... ok           41 ms
     tid                          ... ok           39 ms
     tidscan                      ... ok           49 ms
     tidrangescan                 ... ok           35 ms
     collate.icu.utf8             ... ok           19 ms
     incremental_sort             ... ok          103 ms
parallel group (6 tests):  amutils psql_crosstab collate.linux.utf8 psql rules stats_ext
     rules                        ... FAILED      282 ms
     psql                         ... FAILED      203 ms
     psql_crosstab                ... ok           59 ms
     amutils                      ... ok           26 ms
     stats_ext                    ... ok         1254 ms
     collate.linux.utf8           ... ok          100 ms
test select_parallel              ... ok          724 ms
test write_parallel               ... ok           87 ms
test vacuum_parallel              ... ok          136 ms
parallel group (2 tests):  subscription publication
     publication                  ... ok           72 ms
     subscription                 ... ok           48 ms
parallel group (17 tests):  portals_p2 advisory_lock xmlmap combocid functional_deps tsdicts guc equivclass dependency select_views window bitmapops tsearch indirect_toast cluster foreign_data foreign_key
     select_views                 ... ok          132 ms
     portals_p2                   ... ok           37 ms
     foreign_key                  ... ok          711 ms
     cluster                      ... ok          258 ms
     dependency                   ... ok           83 ms
     guc                          ... ok           74 ms
     bitmapops                    ... ok          226 ms
     combocid                     ... ok           67 ms
     tsearch                      ... ok          233 ms
     tsdicts                      ... ok           71 ms
     foreign_data                 ... ok          418 ms
     window                       ... ok          216 ms
     xmlmap                       ... ok           49 ms
     functional_deps              ... ok           70 ms
     advisory_lock                ... ok           35 ms
     indirect_toast               ... ok          250 ms
     equivclass                   ... ok           79 ms
parallel group (6 tests):  json_encoding jsonpath_encoding jsonpath jsonb_jsonpath json jsonb
     json                         ... ok           88 ms
     jsonb                        ... ok          267 ms
     json_encoding                ... ok           19 ms
     jsonpath                     ... ok           38 ms
     jsonpath_encoding            ... ok           28 ms
     jsonb_jsonpath               ... ok           79 ms
parallel group (18 tests):  prepare returning limit plancache conversion temp copy2 sequence rowtypes with polymorphism truncate largeobject rangefuncs domain plpgsql xml alter_table
     plancache                    ... ok           98 ms
     limit                        ... ok           89 ms
     plpgsql                      ... ok          547 ms
     copy2                        ... ok          149 ms
     temp                         ... ok          129 ms
     domain                       ... ok          226 ms
     rangefuncs                   ... ok          223 ms
     prepare                      ... ok           45 ms
     conversion                   ... ok          101 ms
     truncate                     ... ok          203 ms
     alter_table                  ... ok         1051 ms
     sequence                     ... ok          150 ms
     polymorphism                 ... ok          176 ms
     rowtypes                     ... ok          164 ms
     returning                    ... ok           61 ms
     largeobject                  ... ok          213 ms
     with                         ... ok          175 ms
     xml                          ... ok          609 ms
parallel group (11 tests):  hash_part memoize partition_info reloptions explain compression indexing partition_aggregate partition_prune partition_join tuplesort
     partition_join               ... ok          590 ms
     partition_prune              ... ok          573 ms
     reloptions                   ... ok           56 ms
     hash_part                    ... ok           38 ms
     indexing                     ... ok          495 ms
     partition_aggregate          ... ok          531 ms
     partition_info               ... ok           54 ms
     tuplesort                    ... ok          907 ms
     explain                      ... ok           58 ms
     compression                  ... ok           92 ms
     memoize                      ... ok           49 ms
parallel group (2 tests):  event_trigger oidjoins
     event_trigger                ... ok          113 ms
     oidjoins                     ... ok          210 ms
test fast_default                 ... ok          139 ms
test stats                        ... ok          597 ms
============== shutting down postmaster               ==============

========================
 4 of 211 tests failed. 
========================

**Comment by ahouska** [comment]
If you expect feedback from us, please provide us with some useful information. At least, the branch/tag you are testing and on which platform.

**Comment by hnusttyj530** [comment]
branch:zheap_undo_record_set_pg_14.1
tag:the newst commitid
test method: make check-world
platform: Centos-7.6，x64




***@***.***
 
From: ahouska
Date: 2022-10-21 15:57
To: cybertec-postgresql/postgres
CC: 唐钰小宝; Author
Subject: Re: [cybertec-postgresql/postgres] there are 4 errors in test of regression (Issue #10)
If you expect feedback from us, please provide us with some useful information. At least, the branch/tag you are testing and on which platform.

**Comment by ahouska** [comment]
This is just an experimental (i.e. non-stable) branch.

**Comment by hnusttyj530** [comment]
ok,thx.




***@***.***
 
From: ahouska
Date: 2022-10-21 16:50
To: cybertec-postgresql/postgres
CC: 唐钰小宝; Author
Subject: Re: [cybertec-postgresql/postgres] there are 4 errors in test of regression (Issue #10)
This is just an experimental (i.e. non-stable) branch.
