### ISSUE TITLE
Start Postgresql from Linux

### ISSUE THREAD

**Issue by abgarg2022** [cybertec-postgresql/postgres#11]
Hi Team
I was able to install TDE using wget https://download.cybertec-postgresql.com/postgresql-12.3_TDE_1.0.tar.gz 
Everytime I need to Start/Stop the server I have to issue below command to run psql commands:

`
$ /usr/local/pg12tde/bin/pg_ctl -D /usr/local/pg12tde/data -l /usr/local/pg12tde/data/pg_log/postgresql-%Y-%m-%d_%H%M%S.log start
`
`
$ /usr/local/pg12tde/bin/psql postgres`

Please suggest how can I just go to psql command line like we do in case of normal postgresql installation using below commands:
`
$ sudo systemctl restart postgresql`
`
$ sudo su postgres`
`
 $ psql`

**Comment by laurenz** [comment]
You need to create a systemd unit file like `/etc/systemd/system/postgresql-12.service`. You can adapt the one I find on my system:

```none
[Unit]
Description=PostgreSQL 12 database server
Documentation=https://www.postgresql.org/docs/12/static/
After=syslog.target
After=network.target

[Service]
Type=notify

User=postgres
Group=postgres

# Location of database directory
Environment=PGDATA=/var/lib/pgsql/12/data/

# Where to send early-startup messages from the server (before the logging
# options of postgresql.conf take effect)
# This is normally controlled by the global default set by systemd
# StandardOutput=syslog

# Disable OOM kill on the postmaster
OOMScoreAdjust=-1000
Environment=PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
Environment=PG_OOM_ADJUST_VALUE=0

ExecStart=/usr/pgsql-12/bin/postmaster -D ${PGDATA}
ExecReload=/bin/kill -HUP $MAINPID
KillMode=mixed
KillSignal=SIGINT
 
# Do not set any timeout value, so that systemd will not kill postmaster
# during crash recovery.
TimeoutSec=0

# 0 is the same as infinity, but "infinity" needs systemd 229
TimeoutStartSec=0

TimeoutStopSec=1h

[Install]
WantedBy=multi-user.target
```

**Comment by abgarg2022** [comment]
While trying to setup standby server for replication with primary postgresql server, I am getting below error for TDE Postgresql

`2022-12-26 12:41:19.751 IST [160888] LOG:  database system was shut down in recovery at 2022-12-26 12:40:02 IST
2022-12-26 12:41:19.751 IST [160888] LOG:  entering standby mode
2022-12-26 12:41:19.754 IST [160888] LOG:  redo starts at 0/6000028
2022-12-26 12:41:19.754 IST [160888] LOG:  consistent recovery state reached at 0/7000000
2022-12-26 12:41:19.755 IST [160880] LOG:  database system is ready to accept read only connections
2022-12-26 12:41:19.758 IST [160893] FATAL:  could not connect to the primary server: invalid connection option "channel_binding"
2022-12-26 12:41:19.761 IST [160894] FATAL:  could not connect to the primary server: invalid connection option "channel_binding"
2022-12-26 12:41:24.766 IST [160895] FATAL:  could not connect to the primary server: invalid connection option "channel_binding"
`

**Comment by laurenz** [comment]
Looks like you are trying to connect to a primary server with PostgreSQL v12 or lower.
